name: 'GHAS Alerts Action'
description: 'A custom action to fetch GHAS alerts'
inputs:
  prNumber:
    description: 'Pull Request Number'
    required: true
  repoName:
    description: 'Repository Name'
    required: true
runs:
  using: 'node12'
  main: 'src/index.js'